### ISSUE TITLE
how to add downloading uploading percentage ?

### ISSUE THREAD

**Issue by vaisakhc56** [viperadnan-git/google-drive-telegram-bot#1]

**Comment by viperadnan-git** [comment]
See [pySmartDL](https://www.google.com/search?q=pySmartDL%20Docs) Docs.

Well if you add progress bar. Bot may face `Flood Wait` Errors.

**Comment by vaisakhc56** [comment]
> See [pySmartDL](https://www.google.com/search?q=pySmartDL%20Docs) Docs.
> 
> Well if you add progress bar. Bot may face `Flood Wait` Errors.

that,s not a problem

**Comment by vaisakhc56** [comment]
bro i don't know how add this

**Comment by viperadnan-git** [comment]
> bro i don't know how add this

Learn [Python3](python.org) and See [pySmartDL](https://www.google.com/search?q=pySmartDL%20Docs) Docs.
