### ISSUE TITLE
Issue in gdrive token(bot is not responding on auth token)

### ISSUE THREAD

**Issue by ankit-sinha-18** [viperadnan-git/google-drive-telegram-bot#16]
Bot is not accepting gdrive token,, it is showing auth url and giving token to the bot, it is not responding... Even i tried with another mail too,,,, still the same issue.. What to do?? 
How to fix it??

**Comment by kuro-creator** [comment]
same here. pls fix it ASAP fam

**Comment by Rocky2242** [comment]
Yes same problem here too,,
Bot is not responding when replied with token.

**Comment by sukh3455** [comment]
same problem

**Comment by Rocky2242** [comment]
Any fix ,,pls help..
reply.webcodingplace@gmail.com

**Comment by Rocky2242** [comment]
just fixed this issue ,fork from my repo :https://github.com/Rocky2242/google-drive-telegram-bot-Updated

**Comment by sukh3455** [comment]
i tried rocky's repo Authorization still not working
