### ISSUE TITLE
Token authorization

### ISSUE THREAD

**Issue by denistravis** [viperadnan-git/google-drive-telegram-bot#18]
Hi, your work is awesome, Just some issues after using the bot for a while, the bot suddenly doesn't authorise users, in that it doesn't take the token sent by the users.

**Comment by vaisakhc56** [comment]
i'm facing the same problem

**Comment by ankit-kumar-jat** [comment]
their is a auth key length problem i fix it you can use it from
https://github.com/ankit-kumar-jat/google-drive-telegram-bot
do not deploy using heroku button in readme.md
deploy manually
thank you

**Comment by Rahman510** [comment]
Thank you bro. now it works

**Comment by denistravis** [comment]
> their is a auth key length problem i fix it you can use it from
> https://github.com/ankit-kumar-jat/google-drive-telegram-bot
> do not deploy using heroku button in readme.md
> deploy manually
> thank you

Thanks Sir!!

**Comment by X-Gorn** [comment]
> Thank you bro. now it works



> their is a auth key length problem i fix it you can use it from
> https://github.com/ankit-kumar-jat/google-drive-telegram-bot
> do not deploy using heroku button in readme.md
> deploy manually
> thank you



> their is a auth key length problem i fix it you can use it from
> https://github.com/ankit-kumar-jat/google-drive-telegram-bot
> do not deploy using heroku button in readme.md
> deploy manually
> thank you

Thank You Sir!
