### ISSUE TITLE
It's bug

### ISSUE THREAD

**Issue by vaisakhc56** [viperadnan-git/google-drive-telegram-bot#19]
The authetication code not verifying. can you fix this please

**Comment by ankit-kumar-jat** [comment]
their is a auth key length problem i fix it you can use it from 
https://github.com/ankit-kumar-jat/google-drive-telegram-bot

**Comment by ankit-kumar-jat** [comment]
do not deploy using heroku button
deploy manually 
thank you

**Comment by kushal00011** [comment]
Manually means?

**Comment by ankit-kumar-jat** [comment]
Don't deploy using deploy button in readme file use method provided by heroku

**Comment by kushal00011** [comment]
Do you mean heroku CLI???

**Comment by kushal00011** [comment]
Give a Short guide

**Comment by ankit-kumar-jat** [comment]
You can use heroku CLI

**Comment by kushal00011** [comment]
Or can i connect to GitHub in deploy branch of heroku?

**Comment by ankit-kumar-jat** [comment]
Yes you can

**Comment by kushal00011** [comment]
> Yes you can

Ya did...but still not working

**Comment by vaisakhc56** [comment]
> their is a auth key length problem i fix it you can use it from
> https://github.com/ankit-kumar-jat/google-drive-telegram-bot

ok it's working thanks

**Comment by vaisakhc56** [comment]
its there any bot for mega to drive

**Comment by viperadnan-git** [comment]
Fixed, Use latest version.
