### ISSUE TITLE
HOW TWO REMOVE ❗️ Rate Limit Exceeded

### ISSUE THREAD

**Issue by Mani5GRockers** [viperadnan-git/google-drive-telegram-bot#27]
❗️ Rate Limit Exceeded.
User rate limit exceeded try after 24 hours.

NO LIMITE

HOW TWO ADD

**Comment by viperadnan-git** [comment]
> ❗️ Rate Limit Exceeded.
> User rate limit exceeded try after 24 hours.
> 
> NO LIMITE
> 
> HOW TWO ADD

It's limited by Google Drive.
Only Google can remove it.
