### ISSUE TITLE
heroku no longer works?

### ISSUE THREAD

**Issue by baiguke2019** [viperadnan-git/google-drive-telegram-bot#5]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by baiguke2019** [comment]
heroku work

Thanks

**Comment by AdrianaHernandezs** [comment]
How do you fix it?

**Comment by baiguke2019** [comment]
> How do you fix it?

Check README.md carefully
