### ISSUE TITLE
Commands Not Working For Non Authorized Users

### ISSUE THREAD

**Issue by FristyFlakes** [viperadnan-git/google-drive-telegram-bot#6]
The Bot Works Fine But When New Users Start Up The Bot, No Commands seem to work Other Than /auth..  After authenticating, the commands works afterwards which shouldn't be. Would love if you could fix commands to work for new users so they don't think the bot isn't functioning

**Comment by kushal00011** [comment]
Same issue here

**Comment by FristyFlakes** [comment]
> Same issue here

Fixed already.. Rename admin.py to help.py.

**Comment by kushal00011** [comment]
> > Same issue here
> 
> Fixed already.. Rename admin.py to help.py.

Will it work properly after that?

**Comment by kushal00011** [comment]
But there is no file named admin.py

**Comment by FristyFlakes** [comment]
Rename Utilis.py to Authorize.py

**Comment by FristyFlakes** [comment]
Rename Utils.py to Admins.py.. My bad*

**Comment by viperadnan-git** [comment]
[Fixed](https://github.com/viperadnan-git/google-drive-telegram-bot/commit/28b697bc134836f1dd596fe6312139f2e0c4e949), Use latest Version.
