### ISSUE TITLE
Bot not working in Heroku installation

### ISSUE THREAD

**Issue by stepin104678** [viperadnan-git/google-drive-telegram-bot#9]
Bot deployed using Heroku seems not working

**Comment by NEOIR** [comment]
> Bot deployed using Heroku seems not working

# Same Problem, Bot Not Working

**Comment by viper-adnan** [comment]
We can't help you without logs.

**Comment by viperadnan-git** [comment]
[Probably Fixed](https://github.com/viperadnan-git/google-drive-telegram-bot/commit/28b697bc134836f1dd596fe6312139f2e0c4e949)
